version: 2

project_name: ezycopy

before:
  hooks:
    - go mod tidy

builds:
  - id: ezycopy
    main: .
    binary: ezycopy
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: gupsammy
    name: EzyCopyCLI
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
